sudo: required
services:
  - docker

before_install:
  - docker build -t danielvdm/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true danielvdm/docker-react-udemy npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-udemy"
  env: "Dockerreactudemy-env"
  bucket_name: "elasticbeanstalk-us-east-1-402371977002"
  bucket_path: "docker-react-udemy"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY_SECRET